### ISSUE TITLE
Delete previous version svn tag when releasing new decaf build.

### ISSUE THREAD

**Issue by nerrad** [eventespresso/grunt-wp-plugin-buildmachine#6]
We run into timeout issues when the number of svn tags build up due to the size of the EE core plugin.  It also helps with the time to do a release build if we don't have so many tags.  So an idea is to simply keep the tags folder clean and delete the previous version when doing a new decaf build.

**Comment by sethshoultes** [comment]
Is this something that can be automated or does it needed to be added as an item to a release checklist?

**Comment by joshfeck** [comment]
I believe this is something that can be automated.

**Comment by nerrad** [comment]
@joshfeck it turns out this won't be as easy/quick as I thought to implement.  The best way to implement this would be to fork the existing `grunt-wp-deploy` script being used and add our custom command for deleting the previous tag.  I'd have to work out deriving what that previous tag was.  This is the best way to do things because svn checkout is a beast and doing a separate custom grunt script for this would add significant time to the wp deploy process (as opposed to just building on top of the existing deploy process).

Lately I've been thinking that while our grunt process works well currently, I think I want to avoid doing any thing in it that takes _significant_ time with minimal benefit because grunt isn't really receiving active development now.  webpack/gulp and even plain old npm scripts have become the tools of the trade where the latest development has been happening and I've been thinking about using webpack/npm to create our own deploy mechanisms.

Since it's relatively easy for someone with an svn client to delete old tags every once-and-a-while, I think it'd probably be best if we just do that for the time being.  The time I would spend building this out could be spent better elsewhere I think?  Thoughts?

**Comment by joshfeck** [comment]
Agreed.
